### ISSUE TITLE
Update ZK balances in real-time after auto-minting and receiving

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/democracy#58]
## Work-in-Progress

This issue is still being developed by @cryptogoth and @owonwo 

## Background

This task is part of a larger project to create an interactive web demo / playground for users to learn about zero-knowledge (ZK) assets and gain intuition about them by directly transacting with the contracts on-chain.

You can view the current demo-in-progress at https://zk-transfer.netlify.com

## Description

Currently, after a page is refreshed, it receives 10 units of AAA automatically minted.
However, one has to watch the web console for the message "Minting successful".

This task is to automatically update the ZK balances, using whatever web3 / Javascript / React / responsive web technology of your choice, whenever the numbers are updated on the blockchain.

You may wish to investigate the `web3.js` library, in particular its facility to respond to Solidity events. Solidity events are emitted by AZTEC contracts upon successful minting, and upon transferring.

### Minting and Viewing

As background for this task, you can practice minting new ZK notes to yourself, using the Rinkeby admin account at https://aztec-web.netlify.com and following the web minting instructions in issue #45 .

Also, to test that the confidential transfer occurs when your work for this task is complete, you'll want to refresh https://aztec-web.netlify.com and switch to the admin account in the `Address Book` to see if the new ZK notes are viewable at the bottom of the screen.

## Task Description and Examples

A static demo, created with `react-scripts`, is currently running on: 
https://zk-transfer.netlify.com

In this task, you'll modify the source code in
https://github.com/invisible-college/democracy/tree/master/packages/zk-transfer-web

Your task has two parts, described in more detail below:
1. listen for the Solidity event "updateMintAmount", and update balances when it's received
2. listen for the Solidity event "???", and update balances when it's received

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 100.0 DAI (100.0 USD @ $1.0/DAI)  attached to it as part of the invisible-college fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/invisible-college/democracy/58/4180).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/invisible-college/democracy/58/4180).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $83,737.54 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 6 days, 20 hours from now.
Please review their action plans below:


**1) [evgeniuz](https://gitcoin.co/evgeniuz) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/invisible-college/democracy/58/4180?mutate_worker_action=approve&worker=evgeniuz) | [reject worker](https://gitcoin.co/issue/invisible-college/democracy/58/4180?mutate_worker_action=reject&worker=evgeniuz))_.**

I'm interested to learn more about ZK and would like to work on this bounty. Will start by deploying current version and learning how it works, then will implement required event handling and update.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/invisible-college/democracy/58/4180).

**Comment by cryptogoth** [comment]
hi @evgeniuz glad to have you aboard. Please reach out to us on the gitter channel when you get a chance in the next day or so.

@owonwo wrote the React code and has some experience developing with this stack, including minting / transferring ZK notes. We're both happy to answer questions, brainstorm, give feedback, etc.

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by cryptogoth** [comment]
@evgeniuz we now have a Rinkeby light node for you to use at https://rinkeby.arcology.nyc
which we're able to use to install EVM log filters (for Solidity events).

You'll need to edit the environment variable to use the new host, in the root JS file for the `zk-transfer-web` project.
`window['RINKEBY.ETH_URL'] = 'https://rinkeby.arcology.nyc'`

Here's a gist showing some `ethjs-filter` usage of 1000 blocks at a time.
https://gist.github.com/cryptogoth/13b51540f81e65703ffbf276e5622879

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 10.00000  DAI (10.0 USD @ $1.0/DAI) has been granted to @evgeniuz for this issue from @cryptogoth. ⚡️ 

Nice work @evgeniuz! Your tip has automatically been deposited in the ETH address we have on file.

 * $98289.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by cryptogoth** [comment]
Hi @evgeniuz thanks for asking good questions and uncovering our contract deploy error on Rinkeby.
I'll stop your work on the bounty for now to silence these warnings, and I'll rework the bounties to be a smoother ride.
We'll continue to improve our onboarding process, and any feedback or suggestions you offer are appreciated.

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)

**Comment by gitcoinbot** [comment]
@evgeniuz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=1) | [3 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=3) | [5 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=5) | [10 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=10) | [100 days](https://gitcoin.co/issue/invisible-college/democracy/58/4180?snooze=100)
